[profile.default]
src = 'src'
libs = ['lib']
fallback_oz = true
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[profile.default.zksync]
enable_eravm_extensions = true

[etherscan]
abstractTestnet = { chain = "11124", url = "https://api-sepolia.abscan.org/api", key = "TACK2D1RGYX9U7MC31SZWWQ7FCWRYQ96AD"}
abstractMainnet = { chain = "2741", url = "", key = ""}

[rpc_endpoints]
abstract = "https://api.mainnet.abs.xyz"
abstractTestnet = "https://api.testnet.abs.xyz"