[profile.default]
src = 'src'
libs = ['lib']
solc = "0.8.20"
fallback_oz = true
solc_version = "0.8.20"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[profile.default.zksync]
enable_eravm_extensions = true

etherscan_api_key = "${ETHERSCAN_API_KEY}"

[etherscan]
abstractMainnet = { key = "${ETHERSCAN_API_KEY}" }
abstractTestnet = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
abstract = "https://api.mainnet.abs.xyz"
abstractTestnet = "https://api.testnet.abs.xyz"